version: '3.8'

services:
  app:
    container_name: att-sales-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
